#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

__os_version="$(_get_os)"
case "${__os_version}" in
    Linux*)     __command="sudo service php7.4-fpm reload";;
    Darwin*)    __command="brew services restart php";;
    *)
esac

function laravel_cache_clear() {
  __output=$( php artisan clear-compiled )
  _error_code=$?
  __MSG="Command: tcctl laravel cache clear"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi

  __output=$( eval "$__command" )
  _error_code=$?
  __MSG="Command: $__command"
  if [[ "$_error_code" -eq "0" ]]; then
    echo "Command: $__command successfull"
  else
    _message "$__MSG" "error" "$_error_code"
  fi

  __output=$( php artisan config:cache )
  _error_code=$?
  __MSG="Command: tcctl laravel cache clear"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi

  __output=$( php artisan route:cache )
  _error_code=$?
  __MSG="Command: tcctl laravel cache clear"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi

  __output=$( php artisan event:cache )
  _error_code=$?
  __MSG="Command: tcctl laravel cache clear"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

laravel_cache_clear
