#!/usr/bin/env bash

# shellcheck disable=SC1090,SC2034

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/laravel/cache/functions"

__os_version="$(_get_os)"
case "${__os_version}" in
    Linux*)     __command="sudo service php7.4-fpm reload";;
    Darwin*)    __command="brew services restart php";;
    *)
esac

run_programm_with_error_check "php artisan clear-compiled"
run_programm_with_error_check "php artisan config:clear"
run_programm_with_error_check "php artisan route:clear"
run_programm_with_error_check "php artisan event:clear"
run_programm_with_error_check "php artisan view:clear"
restart_supervisorctl_horizon
