#!/usr/bin/env bash

# Return status of services
# "nginx php7.4-fpm supervisor cron filebeat metricbeat ssh"
names=
STOPPED_SERVICES_NAME=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [[ -n $names ]]; then
  for service_name in $names; do
    if [[ $(sudo systemctl is-active "$service_name") != "active" ]]; then 
      STOPPED_SERVICES_NAME+="$service_name is in-active\n"
    fi
  done
  echo "$STOPPED_SERVICES_NAME"
fi
