FROM alpine:3.13

# Terraform
COPY --from=hashicorp/terraform:1.0.11 /bin/terraform /usr/local/bin/terraform

# Software
RUN apk add --no-cache bash \
  curl \
  openssh \
  jq \
  git

# TCCtl
WORKDIR /cli

COPY . /cli

RUN ln -s /cli/tcctl /usr/local/bin
