#!/usr/bin/env bash

set -e

# cli_dir returns absolute (non-symlink) path to the directory containing
# the *ctl entrypoint script
function cli_dir() {
    # kernel returns the kernel type of the system
    function kernel() {
        uname -s
    }

    # _readlink wraps readlink in Linux or greadlink in Mac OS
    function _readlink() {
        if [[ $(kernel) == "Linux" ]]; then
            readlink "$@"
            return $?
        elif [[ $(kernel) == "Darwin" ]]; then
            greadlink "$@"
            return $?
        fi

        echo "readlink: invalid kernel name $(kernel)" >&2
        return 1
    }

    dirname "$(_readlink -f "$0")"
}

function main() {
    # Expose CLI_DIR variable to subshells and child processes so they can
    # use it to determine path to the ctl directory for importing additional
    # scripts (e.g. the framework/utils script).
    CLI_DIR="$(cli_dir)"
    export CLI_DIR

    # shellcheck disable=SC1091
    # shellcheck source=tc/framework/cli
    source "$CLI_DIR/tc/framework/cli"
    # shellcheck disable=SC1091
    # shellcheck source=tc/framework/complete
    source "$CLI_DIR/tc/framework/complete"
    # shellcheck disable=SC1091
    # shellcheck source=tc/framework/help
    source "$CLI_DIR/tc/framework/help"
    # shellcheck disable=SC1091
    # shellcheck source=tc/framework/utils
    source "$CLI_DIR/tc/framework/utils"

    cli "$@"
}

main "$@"
