#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

function _composer_install_optimized() {
  __output=$(composer install --no-interaction --prefer-dist --optimize-autoloader)
  _error_code=$?
  __MSG="Command: tcctl laravel deployment composer_install_optimized "
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

_composer_install_optimized
