#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

__output=$( git log -1 | sed -n 2p | awk '{ print $3 }' )
_error_code=$?
__MSG="Error getting the last merges"
__MSG+="$__output"
if [ "$_error_code" -eq "0" ]; then
  __pr_commit="$__output"
else
  _message "$__MSG" "error" "$_error_code"
fi
__output=$( git log "${__pr_commit}"..HEAD --ancestry-path --merges --oneline --color | tail -n 1 | awk '{ print $4 }' )
_error_code=$?
__MSG="Error getting the merges branch"
__MSG+="$__output"
if [ "$_error_code" -eq "0" ]; then
  __pr_branch="$__output"
  echo "$__pr_branch"
else
  _message "$__MSG" "error" "$_error_code"
fi
