#!/usr/bin/env bash

function get_source_branch() {
  PR_COMMIT=$(tcctl1 cmd git log -1 | sed -n 6p | awk '{ print $3 }')
  PR_BRANCH=$(tcctl1 cmd git log ${PR_COMMIT}..HEAD --ancestry-path --merges --oneline --color | tail -n 1 | awk '{ print $4 }')
  echo $PR_BRANCH
}

get_source_branch
