#!/usr/bin/env bash

# shellcheck disable=SC1090,SC2086,SC2001

source "$CLI_DIR/tc/framework/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --hash)
    HASH="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

# TODO: source functions

function _get_commits_summary() {
  __output=$(git log --pretty=format:"%s" --no-merges "${1}"...HEAD)
  _error_code=$?
  __MSG="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

_get_commits_summary "${HASH}"
