#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function _get_branch_name() {
  __output=$(git branch | grep '\*' | cut -d ' ' -f2)
  _error_code=$?
  __MSG="Get the current branch name"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    echo "$__output"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

_get_branch_name
