#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

set +e

PARALLEL_PROCESS="8"
QUEUE="deploy"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --parallel-process)
    PARALLEL_PROCESS="$2"
    shift 2
    ;;
    --queue )
    QUEUE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

list="${QUEUE//,/ }"

function _queue_work() {
  __session_name="QUEUES"
  __parallel_process=$1
  if  [[ -z $(command -v byobu) ]]; then
    byobu -2 new-session -d -s $__session_name
    _error_code="$?"
    if [[ "$_error_code" -gt "0" ]]; then
      exit 1
    fi
  else
    exit 1
  fi
  for ((i=1;i<="$__parallel_process";i++)); do
    for item in $list; do
      byobu new-window -t $__session_name "php artisan queue:work --force --queue=$item"
      _error_code=$(( "$_error_code" + "$?" ))
      if [[ "$_error_code" -gt "0" ]]; then
        exit 1
      fi
    done
  done
  php artisan tc:once_run --during_deploy --force
  _error_code=$(( "$_error_code" + "$?" ))
  if [[ "$_error_code" -gt "0" ]]; then
    exit 1
  fi
  php artisan tc:devops:queues_state --queue=deploy --terminate-when-empty=true
  _error_code=$(( "$_error_code" + "$?" ))
  if [[ "$_error_code" -gt "0" ]]; then
    exit 1
  fi
  byobu kill-session -t "$__session_name"
  _error_code=$(( "$_error_code" + "$?" ))
  if [[ "$_error_code" -gt "0" ]]; then
    exit 1
  fi
  __MSG="Command: tcctl laravel deployment queue_work"
  if [ "$_error_code" -eq "0" ]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$PARALLEL_PROCESS" ]; then
  __MSG="Command: tcctl laravel deployment queue_work missed --parallel-process"
  _message "$__MSG" "error" "$_error_code"
elif [ -z "$QUEUE" ]; then
  __MSG="Command: tcctl laravel deployment queue_work missed --queue"
  _message "$__MSG" "error" "$_error_code"
else
  _queue_work "$PARALLEL_PROCESS"
fi
