#!/usr/bin/env bash

function run_migrate_and_during_deploy() {
  tcctl php artisan migrate --force
  PROCCESS_COUNT=8
  SESSION_NAME="QUEUES"
  tcctl cmd byobu -2 new-session -d -s $SESSION_NAME
  for ((i=1;i<=$PROCCESS_COUNT;i++));
  do
    tcctl cmd byobu new-window -t $SESSION_NAME "php artisan queue:work --force --queue=deploy"
  done
  tcctl php artisan tc:once_run --during_deploy --force
  tcctl php artisan tc:devops:queues_state --queue=deploy --terminate-when-empty=true
  tcctl cmd byobu kill-session -t $SESSION_NAME
}

run_migrate_and_during_deploy
