#!/usr/bin/env bash

source "./cli/tc/framework/functions"

function update_project() {
  OS=$1
  APP_ENV=$2
  COMPOSER_LOCK=$(tcctl laravel deployment file_md5_sum composer.lock $OS)
  PACKAGE_LOCK=$(tcctl laravel deployment file_md5_sum yarn.lock $OS)
  BRANCH=$(tcctl cmd git branch | grep \* | cut -d ' ' -f2)
  if [[ ! -d "vendor" ]]; then
    echo "We need to install composer to run the following commands"
    tcctl cmd composer install --no-interaction --prefer-dist --optimize-autoloader
    tcctl cmd yarn ci
  fi
  tcctl php artisan tc:devops:queues_state --terminate-when-empty=true
  tcctl php artisan horizon:pause

  tcctl php artisan config:clear
  tcctl php artisan route:clear
  tcctl php artisan view:clear
  tcctl php artisan event:clear
  tcctl php artisan clear-compiled

  if [[ -z "$(tcctl cmd git status --short)" ]]; then
    echo "working tree clean"
  else
    echo "working tree isn't clean"
    tcctl cmd git status --short
    tcctl cmd git reset --hard HEAD
    tcctl cmd git clean -f -d
    echo "We fix it ;)"
  fi

  tcctl cmd git pull origin $BRANCH --tags
  tcctl cmd composer install --no-interaction --prefer-dist --optimize-autoloader

  if [[ $PACKAGE_LOCK != "$(tcctl laravel deployment file_md5_sum yarn.lock $OS)" && $APP_ENV != "production" && $APP_ENV != "staging" ]]; then
    tcctl cmd yarn ci
  fi
}

update_project $1 $2
