#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"

find_string=
append_string=
file_name=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -f "$file_name" ]; then
  _append_string_after "$find_string" "$append_string" "$file_name"
else
  __MSG="File $file_name doesn't exists"
  _message "$__MSG" "error"
fi
