#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --filename)
    FILENAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

_check_bin_file "$FILENAME"
