#!/usr/bin/env bash

# shellcheck disable=SC2063,SC1090

source "$CLI_DIR/tc/framework/functions"

function check_deployment_type() {
  __branch=$(tcctl run git branch | grep \* | cut -d ' ' -f2)
  __repository_url=$(tcctl run git config --get remote.origin.url)
  __repository_tmp_dir="/tmp/$(date +%Y%m%d-%H%M%S)"
  __output=$( git clone --depth 1 "$__repository_url" -b "$__branch" "$__repository_tmp_dir" )
  _error_code=$?
  __MSG="Command: tcctl helpers $__repository_url clone to tmp dir"
  __MSG+="$__output"
  if [[ "$_error_code" -eq "0" ]]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
  __output=$( php artisan tc:devops:migrations_state \
                    --base-path="${__repository_tmp_dir}" \
                    --non-verbose )
  _error_code=$?
  __MSG="Command: tcctl helpers $__repository_url check migrations state"
  __MSG+="$__output"
  if [[ "$_error_code" -eq "0" ]]; then
    _message "$__MSG"
    __deploy_tasks="$__output"
    if [[ $__deploy_tasks -gt "0" ]]; then
      echo "true"
    fi
  else
    _message "$__MSG" "error" "$_error_code"
  fi
  rm -rf "$__repository_tmp_dir"
}

check_deployment_type
