#!/usr/bin/env bash

# shellcheck disable=SC1090,SC2034,SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/slack/functions"

CHANNEL="#devops-notifications"
FILE="/tmp/commits_summary"
COLOR="#6dc56d"
URL=""

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    --message)
    MESSAGE="$2"
    shift 2
    ;;
    --color)
    COLOR="$2"
    shift 2
    ;;
    --url)
    URL="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function commits_summary_format() {
  grep -E -oh 'TC-[0-9]+' /tmp/commits_summary \
    | sort -u \
    | awk '{print "https://tenantcloud.atlassian.net/browse/" $1}'
}

commits_summary_format
MESSAGE="The list of solved problems when deploying (:host: $URL ):\n"
MESSAGE+="$(commits_summary_format)"

slack_send_message "$MESSAGE" "$CHANNEL" "$COLOR" "$FILE" "$URL"
