#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091,SC2120,SC2048,SC2086,SC2034

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/slack/functions"

CHANNEL="#devops-notifications"
MESSAGE="Hostname: $(hostname)"
FILE="/tmp/commits_summary"
COLOR="#6dc56d"
URL=""

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    --message)
    MESSAGE="$2"
    shift 2
    ;;
    --color)
    COLOR="$2"
    shift 2
    ;;
    --url)
    URL="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function commits_summary() {
  __latest_commit=$( git log -3 --pretty=format:"%h" | tail -n 1 )
  __commits_summary=$( git log --pretty=format:"%s" --no-merges "$__latest_commit"...HEAD )
  printf %s "$__commits_summary" > /tmp/commits_summary
}

function commits_summary_format() {
  grep -E -oh 'TC-[0-9]+' /tmp/commits_summary \
    | sort -u \
    | awk '{print "https://tenantcloud.atlassian.net/browse/" $1}'
}

commits_summary

slack_file_upload "$CHANNEL" "$MESSAGE" "$FILE"

commits_summary_format
MESSAGE="The list of solved problems when deploying (:host: $URL ):\n"
MESSAGE+="$(commits_summary_format)"

slack_send_message "$MESSAGE" "$CHANNEL" "$COLOR" "$FILE" "$URL"
