#!/usr/bin/env bash

# shellcheck disable=SC2063,SC1091,SC2120,SC2086,2048

source "$CLI_DIR/tc/framework/functions"

function commits_summary() {
  __commits_summary=$( git log -1 --pretty=format:"%b"  $* )
  echo $__commits_summary
  printf %s "$__commits_summary" > /tmp/commits_summary
}

commits_summary
