#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091,SC2120,SC2048,SC2086,SC2034

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/slack/functions"

CHANNEL="#devops-notifications"
MESSAGE="Hostname: $(hostname)"
FILE="/tmp/commits_summary"
COLOR="#6dc56d"
URL=""
TAG1=$( git log -1 | sed -n '2p' | awk '{ print $2 }' )
TAG2="HEAD"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    --message)
    MESSAGE="$2"
    shift 2
    ;;
    --color)
    COLOR="$2"
    shift 2
    ;;
    --url)
    URL="$2"
    shift 2
    ;;
    --tag1)
    TAG1="$2"
    shift 2
    ;;
    --tag2)
    TAG2="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function commits_summary() {
  tag1="$1"
  tag2="$2"
  __commits_summary=$( git log --pretty=format:"%s" --no-merges "$tag1"..."$tag2" )
  printf %s "$__commits_summary" | grep -v "Merge branch" > /tmp/commits_summary
}

function commits_summary_format() {
  grep -E -oh '[A-Z]+\-[0-9]+' /tmp/commits_summary \
    | sort -u \
    | awk '{print "https://tenantcloud.atlassian.net/browse/" $1}'
}

commits_summary "$TAG1" "$TAG2"

slack_file_upload "$CHANNEL" "$MESSAGE" "$FILE"

commits_summary_format
MESSAGE="The list of solved problems when deploying (:host: $URL ):\n"
MESSAGE+="$(commits_summary_format)"

slack_send_message "$MESSAGE" "$CHANNEL" "$COLOR" "$FILE" "$URL"
