#!/usr/bin/env bash

# shellcheck disable=SC2063,SC1091

source "$CLI_DIR/tc/framework/functions"

function commits_summary_format() {
  grep -E -oh 'TC-[0-9]+' /tmp/commits_summary \
    | sort -u \
    | awk '{print "https://tenantcloud.atlassian.net/browse/" $1}'
}

commits_summary_format
