#!/usr/bin/env bash

# shellcheck disable=SC1090,SC2034,SC2154

source "$CLI_DIR/tc/framework/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --along_path)
    ALONG_PATH="$2"
    shift 2
    ;;
    --dir_name)
    DIR_NAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _create_dir_along_path() {
  ALONG_PATH=$1
  DIR_NAME=$2
  if [ ! -d "$1"/"$2" ]; then
    mkdir "$1"/"$2"
    _error_code=$?
  __MSG="Command: tcctl helpers create $2 along path $1"
  __MSG+="$__output"
    if [ $_error_code -eq "0" ]; then
      _message "$__MSG"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  fi
}

if [ -z "$ALONG_PATH" ]; then
  __MSG="Command: tcctl helpers create_dir_along_path missed --along_path"
  _message "$__MSG" "error" "$_error_code"
elif [ -z "$DIR_NAME" ]; then
   __MSG="Command: tcctl helpers create_dir_along_path missed --dir_name"
  _message "$__MSG" "error" "$_error_code"
else
  _create_dir_along_path "$ALONG_PATH" "$DIR_NAME"
fi
