#!/usr/bin/env bash

# shellcheck disable=SC1090,SC2034,SC2154

source "$CLI_DIR/tc/framework/functions"

along_path=
dir_name=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _create_dir_along_path() {
  __along_path=$1
  __dir_name=$2
  if [ -d "$__along_path" ]; then
    mkdir "$__along_path"/"$__dir_name"
    _error_code=$?
    __MSG="Create $__dir_name dir along $__along_path path"
    __MSG+="$__output"
    if [ "$_error_code" -eq "0" ]; then
      _message "$__MSG"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  else
    __MSG="$__along_path path doesn't exist"
    _message "$__MSG" "error" "$_error_code"
  fi
}

_create_dir_along_path "$along_path" "$dir_name"
