#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function file_md5_sum() {
  OS=$( _get_os )
  if [[ $OS == "Linux" ]]; then
    __output=$( md5sum $1 )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl helpers $1 md5sum\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      FILE_MD5_SUM=$( md5sum $1 | awk '{print $1}' )
    else
      _message_error "$__MSG"
    fi
  fi
  if [[ $OS == "Darwin" ]]; then
    __output=$( md5 $1 )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl helpers $1 md5_sum\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      FILE_MD5_SUM=$( md5 $1 | awk '{print $4}' )
    else
      _message_error "$__MSG"
    fi
  fi
  echo $FILE_MD5_SUM

}

file_md5_sum $1
