#!/usr/bin/env bash

function _check_bin_file() {
  __output=$(command -v "$1")
  _error_code=$?
  __MSG="Command: tcctl helpers check_bin_file => $1 "
  __MSG+="$__output"
  if [ $_error_code -gt "0" ]; then
    echo "bin file $1 is missing"
    _message "$__MSG" "error" "$_error_code"
  fi
}
