#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

dir_path=
permission=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -d "$dir_path" ]; then
  _set_dir_permission "$dir_path" "$permission"
else
  __MSG="Directory $dir_path doesn't exists"
  _message "$__MSG" "error"
fi
