#!/usr/bin/env bash

# shellcheck disable=SC2063,SC2034

function update_project() {
  APP_ENV=$( tcctl helpers env get --key APP_ENV --env .env )
  COMPOSER_LOCK=$( tcctl helpers file_md5_sum --filename composer.lock )
  PACKAGE_LOCK=$( tcctl helpers file_md5_sum --filename yarn.lock )
  BRANCH=$(tcctl run git branch | grep \* | cut -d ' ' -f2)
  if [[ ! -d "vendor" ]]; then
    echo "We need to install composer to run the following commands"
    tcctl run composer install --no-interaction --prefer-dist --optimize-autoloader
    tcctl run yarn ci
  fi
  tcctl php artisan tc:devops:queues_state --terminate-when-empty=true
  tcctl php artisan horizon:pause

  tcctl php artisan config:clear
  tcctl php artisan route:clear
  tcctl php artisan view:clear
  tcctl php artisan event:clear
  tcctl php artisan clear-compiled

  if [[ -z "$(tcctl run git status --short)" ]]; then
    echo "working tree clean"
  else
    echo "working tree isn't clean"
    tcctl run git status --short
    tcctl run git reset --hard HEAD
    tcctl run git clean -f -d
    echo "We fix it ;)"
  fi

  tcctl run git pull origin "$BRANCH" --tags
  tcctl run composer install --no-interaction --prefer-dist --optimize-autoloader
}

update_project
