#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"
source "$CLI_DIR/tc/app/vault/functions"

secret_path=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _secret_delete() {
  _check_bin_file vault
  VAULT_TOKEN=$(_vault_get_token)
  export VAULT_TOKEN
  __secret_path=$1
  vault kv metadata delete "$__secret_path"
  _error_code=$?
  if [ $_error_code -gt "0" ]; then
    __MSG="Error while deleting $__secret_path"
    _message "$__MSG" "error" "$_error_code"
  fi
}

_secret_delete "$secret_path"
