#!/usr/bin/env bash

# shellcheck source=../../framework/functions
# shellcheck disable=SC1091
source "${CLI_DIR}/tc/framework/functions"

for __param in "$@"; do
  __parameters+="$__param "
done

__output=$( php artisan "$__parameters" 2>&1 )
export _error_code=$?
__MSG="Command: \033[36mphp artisan $__parameters\033[39m\n"
__MSG+="$__output"

if [ $_error_code -eq "0" ]; then
  message_info "$__MSG"
else
  message_error "$__MSG"
fi

