#!/usr/bin/env bash

# shellcheck source=../../framework/functions
# shellcheck disable=SC1091
source "${CLI_DIR}/tc/framework/functions"

for __param in "$@"; do
  __parameters+="$__param "
done

__output=$( php artisan "$__parameters" 2>&1 )
export _error_code=$?
__MSG="Command: php artisan $__parameters"
__MSG+="$__output"

if [ $_error_code -eq "0" ]; then
  echo "$__output"
else
  _message "$__MSG" "error" "$_error_code"
fi
