#!/usr/bin/env bash

script_path=
__cron_folder="/etc/cron.d"
__job_name="tc-job-$(date +'%s')"

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -z "$exec_time" ]; then
  exec_time="$(date -d '5 minutes' +'%M %H %d %m %u')"
fi

sudo tee -a "${__cron_folder}/${__job_name}" > /dev/null << EOF
# Job name: ${__job_name}
${exec_time}    ${USER}     ${script_path}
$(date -d '1 day' +'%M %H %d %m %u')    root     rm ${__cron_folder}/${__job_name}
EOF
sudo chmod +x "${__cron_folder}/${__job_name}"