#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/laravel/functions"

bitbucket_username=
repo_slug=
branch_from=
branch_to=
response_file=pr-$(date +'%Y-%m-%d_%H-%M-%S').json
bitbucket_client_id=
bitbucket_client_secret=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

_send_pull_request "$bitbucket_username" \
 "$repo_slug" \
 "$branch_from" \
 "$branch_to" \
 "$response_file" \
 "$bitbucket_client_id" \
 "$bitbucket_client_secret"
