#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function get_value_from_env() {
    VARIABLE=$1
    FILENAME=$2
    if [[ ! -f "$2" ]]; then
      FILENAME=".env"
    fi
    __output=$( sed -n -e "s/^\s*$VARIABLE\s*=//p" $FILENAME )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl helpers get value from $1\033[39m\n"
    __MSG+="$__output"
    if [ $_error_code -eq "0" ]; then
      if [[ -z "$__output" ]]; then
        _message_warning "$__MSG"
        exit 1
      else
        echo $__output
      fi
    else
      _message_error "$__MSG"
    fi
}

get_value_from_env $1 $2
