#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

PARAM_ENV="${PARAM_ENV:-.env}"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --key)
    KEY_NAME="$2"
    shift 2
    ;;
    --env)
    ENV_FILE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function get_value_from_env() {
  __key_name=$1
  __env_file=$2
  if [[ ! -f "$2" ]]; then
    _message "$__MSG" "error" "$_error_code"
  fi
  __output=$( sed -n -e "s/^\s*$__key_name\s*=//p" "$__env_file" )
  _error_code=$?
  __MSG="Command: tcctl helpers get value from $1"
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    if [[ -z "$__output" ]]; then
      _message "$__MSG" "warning" "$_error_code"
      exit 1
    else
      echo "$__output"
    fi
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$KEY_NAME" ]; then
  __MSG="Command: tcctl helpers env get missed --key"
  _message "$__MSG" "error" "$_error_code"
else
  get_value_from_env "$KEY_NAME" "$ENV_FILE"
fi
