#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

ENV="${ENV:-.env}"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --key)
    KEY="$2"
    shift 2
    ;;
    --env)
    ENV="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function get_value_from_env() {
  KEY=$1
  ENV=$2
  if [[ ! -f "$2" ]]; then
    _message "$__MSG" "error" "$_error_code"
  fi
  __output=$( sed -n -e "s/^\s*$KEY\s*=//p" "$ENV" )
  export _error_code=$?
  __MSG="Command: tcctl helpers get value from $1"
  __MSG+="$__output"
  if [ $_error_code -eq "0" ]; then
    if [[ -z "$__output" ]]; then
      _message "$__MSG" "warning" "$_error_code"
      exit 1
    else
      echo "$__output"
    fi
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$KEY" ]; then
  __MSG="Command: tcctl helpers env get missed --key"
  _message "$__MSG" "error" "$_error_code"
else
  get_value_from_env "$KEY" "$ENV"
fi
