#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"

key=
key_value=
file=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _set_value_to_env() {
  __key_name=$1
  __key_value=$2
  __file_name=$3
  __command=$(_get_sed)
  __command+=" -i 's/^$__key_name=.*/$__key_name=$__key_value/' $__file_name"
  __output=$(eval "$__command")
  _error_code=$?
  __MSG="Set ${__key_name} key to ${__file_name} file"
  __MSG+="$__output"
  if [[ "$_error_code" -eq "0" ]]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -f "$file" ]; then
  _set_value_to_env "$key" "$key_value" "$file"
else
  __MSG="File $file doesn't exists"
  _message "$__MSG" "error"
fi
