#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"

key=
key_value=
env=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _set_value_to_env() {
  __key_name=$1
  __key_value=$2
  __env_file=$3
  __command=$(_get_sed)
  __command+=" -i 's/^$__key_name=.*/$__key_name=$__key_value/' $__env_file"
  __output=$(eval "$__command")
  _error_code=$?
  __MSG="Set ${__key_name} key to ${__env_file} file"
  __MSG+="$__output"
  if [[ "$_error_code" -eq "0" ]]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -f "$env" ]; then
  _set_value_to_env "$key" "$key_value" "$env"
else
  __MSG="File $env doesn't exists"
  _message "$__MSG" "error"
fi
