#!/usr/bin/env bash

if [[ $@ == 'dashboard' ]]; then
  docker exec tc-home-mysql mysql -h127.0.0.1 -uroot -proot -e "CREATE USER 'read'@'%' IDENTIFIED BY 'read';"
  docker exec tc-home-mysql mysql -h127.0.0.1 -uroot -proot -e "GRANT SELECT, SHOW VIEW ON *.* TO 'read'@'%';"
  docker exec tc-home-mysql mysql -h127.0.0.1 -uroot -proot -e "FLUSH PRIVILEGES;"
  docker exec tc-home-php composer install
  docker exec tc-home-php php artisan migrate
  docker exec tc-home-php php artisan db:seed
  docker exec tc-home-node yarn
  docker exec tc-home-node yarn release
  docker exec tc-home-node yarn symlink
elif [[ $@ == 'promo' ]]; then
  docker exec tc-www-php composer install
  docker exec tc-www-node yarn
  docker exec tc-www-node yarn release
  docker exec tc-www-node yarn symlink
else echo "Please enter dashboard or promo value, for example - tcctl install_docker dashboard"
fi
