#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$CLI_DIR/tc/framework/functions"

text=
type="info"
errorcode="0"

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -n "$text" ]; then
  _message "$text" "$type" "$errorcode"
fi
