#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

for __param in "$@"; do
  __parameters+="$__param "
done

__output="$( $__parameters 2>&1 )"
_error_code=$?
__MSG="Command: cmd run $__parameters"
__MSG+="$__output"

if [ "$_error_code" -eq "0" ]; then
  echo "$__output"
else
  _message "$__MSG" "error" "$_error_code"
fi
