#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"

for __param in "$@"; do
  __parameters+="$__param "
done

__output="$( $__parameters 2>&1 | tee /dev/fd/5; exit "${PIPESTATUS[0]}")"
__error_code=$?
__MSG="Command: cmd run $__parameters"
__MSG+="$__output"

if [ "$__error_code" -eq "0" ]; then
  echo "$__output"
else
  _message "$__MSG" "error" "$__error_code"
fi
