#!/bin/bash

source "./tc/framework/functions"
source "./tc/app/aws/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  --profile)
  PROFILE="$2"
  shift
  shift
  ;;
  --repository)
  REPOSITORY="$2"
  shift
  shift
  ;;
  --leave-last-image)
  LEAVE_LAST_IMAGE="$2"
  shift
  shift
  ;;
  --exclude-tag)
  EXCLUDE_TAG="$2"
  shift
  shift
  ;;
  *)
  ;;
esac
done

_get_ecr_images_count
_parse_ecr_image_count

__MSG="\033[36mImages with next tags will be removed from AWS ECR ${REPOSITORY} repository\033[39m\n\
Excluded tag: $EXCLUDE_TAG"
_message_info "$__MSG"

if [ ! -z "$EXCLUDE_TAG" ]
then
  tag_delete=$(aws ecr describe-images --repository-name ${REPOSITORY} --profile ${PROFILE} \
  --image-ids imageTag=$EXCLUDE_TAG --output text | awk {'print $3'})
  array=( "${array[@]/$tag_delete}" )
fi

for l in "${array[@]}"
do
  for i in $l
  do
    oldImageDigest=`aws ecr describe-images --repository-name ${REPOSITORY} --profile ${PROFILE} \
    --output text | grep -w $i | awk {'print $2'}`
    oldImageTags=`aws ecr describe-images --repository-name ${REPOSITORY} --profile ${PROFILE} \
    --output text --image-ids imageDigest=${oldImageDigest}`
    echo $oldImageTags | awk {'print $8'}
  done
done
