#!/bin/bash

# shellcheck source=./tc/framework/functions
# shellcheck source=./tc/app/aws/functions
# shellcheck disable=SC1091,SC2154,SC2034

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/aws/functions"

set +e

PROFILE="${PROFILE:-default}"
LEAVE_LAST_IMAGE="${LEAVE_LAST_IMAGE:-5}"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  --profile)
  PROFILE="$2"
  shift 2
  ;;
  --repository)
  REPOSITORY="$2"
  shift 2
  ;;
  --leave-last-image)
  LEAVE_LAST_IMAGE="$2"
  shift 2
  ;;
  --exclude-tag)
  EXCLUDE_TAG="$2"
  shift 2
  ;;
  *)
  ;;
esac
done

# Function get exclude image tag
function _get_exclude_tag_image_digest() {
  __output=$( echo "$1" \
  | jq -r '.[] | (.imagePushedAt|tostring) + " " + .imageDigest + " " + .imageTags[0]' \
  | grep "$EXCLUDE_TAG" | awk '{print $2}' )
  export _error_code=$?
  __MSG="\033[36mImages with next tags will be removed from AWS ECR ${REPOSITORY} repository\033[39m\n"
  __MSG+="$__output"
  if [[ $_error_code -eq "0" ]]; then
    export _exclude_tag_image_digest="$__output"
  else
    _message_error "$__MSG"
  fi
}

# Delete last N images from json
_parsed_json=$(_delete_last_n_images_from_json "$(_describe_ecr_images "$REPOSITORY" "$PROFILE")" "$LEAVE_LAST_IMAGE")

if [ -z "$REPOSITORY" ]; then
  __MSG="Command: tcctl aws get_ecr_images_list missed --repository arg"
  _message_error "$__MSG"
else
  if [ -z "$EXCLUDE_TAG" ]; then
    # Print deleted images tags
    _get_old_image_tags "$_parsed_json"
    # Create array with images digest
    _array=$( _get_old_image_digest "$_parsed_json" )
    # Delete AWS ECR images from array
    for l in "${_array[@]}"
    do
      for i in $l
      do
        _delete_old_ecr_images
      done
    done
  else
    # Print deleted images tags without excluded tag
    _get_old_image_tags "$_parsed_json" | sed "/$EXCLUDE_TAG/d"
    # Get excluded image digest
    _get_exclude_tag_image_digest "$_parsed_json"
    # Create array with images digest
    _array=$( _get_old_image_digest "$_parsed_json" | sed "/$_exclude_tag_image_digest/d" )
    # Delete AWS ECR images from array
    for l in "${_array[@]}"
    do
      for i in $l
      do
        _delete_old_ecr_images
      done
    done
  fi
fi
