#!/bin/bash

# shellcheck source=./tc/framework/functions
# shellcheck source=./tc/app/aws/functions
# shellcheck disable=SC1091,SC2154,SC2034

source "./tc/framework/functions"
source "./tc/app/aws/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  --profile)
  PROFILE="$2"
  shift
  shift
  ;;
  --repository)
  REPOSITORY="$2"
  shift
  shift
  ;;
  --leave-last-image)
  LEAVE_LAST_IMAGE="$2"
  shift
  shift
  ;;
  *)
  ;;
esac
done

_get_old_image_tags
_get_old_image_digest

for l in "${_array[@]}"
do
  for i in $l
  do
    _delete_old_ecr_images
  done
done
