#!/bin/bash

# shellcheck source=./tc/framework/functions
# shellcheck source=./tc/app/aws/functions
# shellcheck disable=SC1091

source "./tc/framework/functions"
source "./tc/app/aws/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  --profile)
  PROFILE="$2"
  shift
  shift
  ;;
  --repository)
  REPOSITORY="$2"
  shift
  shift
  ;;
  --leave-last-image)
  LEAVE_LAST_IMAGE="$2"
  shift
  shift
  ;;
  --exclude-tag)
  EXCLUDE_TAG="$2"
  shift
  shift
  ;;
  *)
  ;;
esac
done

_get_old_image_tags | sed "/$EXCLUDE_TAG/d"

function _get_ecr_images_list_exclude() {
  __output=$( _get_ecr_images_list | jq -r ".[].imageDigest" | sed "/$_exclude_tag_image_digest/d" )
  export _error_code=$?
  __MSG="Command: \033[36mtcctl aws ecr list-images\033[39m\n"
  __MSG+="$__output"
  if [[ $_error_code -eq "0" ]]; then
    _array="$__output"
  else
    _message_error "$__MSG"
  fi
}

_get_exclude_tag_image_digest
_get_ecr_images_list_exclude

for l in "${_array[@]}"
do
  for i in $l
  do
    _delete_old_ecr_images
  done
done
