#!/usr/bin/env bash

db_identifier=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -n "$db_identifier" ]; then
  __output=$( aws rds describe-db-instances \
    --db-instance-identifier "$db_identifier" \
    | jq -r ".DBInstances[].DBInstanceStatus" )
  __error_code=$?
  if [ "$__error_code" -eq "0" ]; then
    echo "$__output"
  fi
fi