#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/aws/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --db-identifier)
    DB_IDENTIFIER="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

if [ -z "$DB_IDENTIFIER" ]; then
  __MSG="Command: tcctl aws get_replicas_name missed --db-identifier"
  _message "$__MSG" "error" "$_error_code"
else
  get_replicas_name "$DB_IDENTIFIER"
fi
