#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

auth_type=
secret_path=
token=
name=
pass=
addr=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

_check_bin_file vault
_vault_authorization "$auth_type" "$name" "$pass" "$token" "$addr"
vault secrets disable "$secret_path" > /dev/null 2>&1
_error_code=$?
if [ $_error_code -gt "0" ]; then
  __MSG="Error while deleting $secret_path"
  _message "$__MSG" "error" "$_error_code"
fi
