#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --secret_path)
    SECRET_PATH="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _secret_delete() {
  _check_bin_file vault
  VAULT_TOKEN=$(tcctl vault token)
  export VAULT_TOKEN
  __secret_path=$1
  __output=$( vault secrets disable "$__secret_path" )
  _error_code=$?
  __MSG="Command: tcctl vault $__secret_path delete "
  __MSG+="$__output"
  if [ $_error_code -gt "0" ]; then
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$SECRET_PATH" ]; then
  __MSG="Command: tcctl vault secret delete missed --secret_path"
  _message "$__MSG" "error" "$_error_code"
else
  _secret_delete "$SECRET_PATH"
fi
