#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

KV_VERSION="2 kv"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --secret-path)
    SECRET_PATH="$2"
    shift 2
    ;;
    --kv_version)
    KV_VERSION="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _secret_enable() {
  _check_bin_file vault
  tcctl vault token
  __secret_path=$1
  __kv_version=$2
  __output=$( vault secrets enable -path="$__secret_path" -version="$__kv_version" 2>&1 )
  _error_code=$?
  __MSG="Command: tcctl vault $__secret_path enable "
  __MSG+="$__output"
  if [ $_error_code -eq "0" ]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$SECRET_PATH" ]; then
  __MSG="Command: tcctl vault secret enable --secret-project"
  _message "$__MSG" "error" "$_error_code"
else
  _secret_enable "$SECRET_PATH" "$KV_VERSION"
fi
