#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/helpers/functions"

VAULT_CONFIG_FILE=~/.vault-configuration
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --vault-addr)
    VAULT_ADDR="$2"
    shift 2
    ;;
    --vault-name)
    VAULT_NAME="$2"
    shift 2
    ;;
    --vault-password)
    VAULT_PASSWORD="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _vault_config() {
  _check_bin_file vault
  VAULT_ADDR=$1
  VAULT_NAME=$2
  VAULT_PASSWORD=$3
  if grep -q "export VAULT_ADDR=" "$VAULT_CONFIG_FILE"; then
    _replace_string_with_escapes \
    "^export VAULT_ADDR=.*" \
    "export VAULT_ADDR=$VAULT_ADDR" \
    $VAULT_CONFIG_FILE
  else
    echo 'export VAULT_ADDR='"$VAULT_ADDR" >> $VAULT_CONFIG_FILE
  fi
  if grep -q "export VAULT_NAME=" "$VAULT_CONFIG_FILE"; then
    _replace_string_with_escapes \
    "^export VAULT_NAME=.*" \
    "export VAULT_NAME=$VAULT_NAME" \
    $VAULT_CONFIG_FILE
  else
    echo 'export VAULT_NAME='"$VAULT_NAME" >> $VAULT_CONFIG_FILE
  fi
  if grep -q "export VAULT_PASSWORD="  "$VAULT_CONFIG_FILE"; then
    _replace_string_with_escapes \
    "^export VAULT_PASSWORD=.*" \
    "export VAULT_PASSWORD=$VAULT_PASSWORD" \
    "$VAULT_CONFIG_FILE"
  else
    echo 'export VAULT_PASSWORD='"$VAULT_PASSWORD" >> $VAULT_CONFIG_FILE
  fi
  # shellcheck source=/dev/null
  source $VAULT_CONFIG_FILE
  _error_code=$?
  __MSG="Command: tcctl vault config"
  if [[ "$_error_code" -eq "0" ]]; then
    _message "$__MSG"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
  echo "Add vault credentials to profile is successfully"
}

if [ -z "$VAULT_NAME" ]; then
  __MSG="Command: tcctl vault config missed --vault-name"
  _message "$__MSG" "error" "$_error_code"
elif [ -z "$VAULT_PASSWORD" ]; then
  __MSG="Command: tcctl vault config missed --vault-password"
  _message "$__MSG" "error" "$_error_code"
else
  _vault_config "$VAULT_ADDR" "$VAULT_NAME" "$VAULT_PASSWORD"
fi
