#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

env_1=
env_2=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _vault_diff() {
  _check_bin_file vault
  env_1=$1
  env_2=$2
  __output=$(diff -y --suppress-common-lines "$env_1" "$env_2")
  _error_code=$?
  __MSG="Output the difference between two files"
  if [ "$_error_code" -eq "0" ] | [ "$_error_code" -eq "1" ]; then
    echo "$__output" | column -t
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

_vault_diff "$env_1" "$env_2"
