#!/usr/bin/env bash

function vault_diff() {
  MSG="Сomparison completed"
  ENV_FILE=$1
  DIFF=$(diff -y --suppress-common-lines /tmp/.env.vault $ENV_FILE | column -t)
  echo "$DIFF"
}

vault_diff $1
