#!/usr/bin/env bash

# shellcheck disable=SC2124,SC1091,SC2119

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

secret_path=
env=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

function _vault_get() {
  _check_bin_file vault
  VAULT_TOKEN=$(_vault_get_token)
  export VAULT_TOKEN
  __secret_path=$1
  __local_path=$2
  __output=$(vault kv get "$__secret_path" 2>&1)
  _error_code=$?
  __MSG="Get keys from ${__secret_path} - "
  __MSG+="$__output"
  if [ "$_error_code" -eq "0" ]; then
    vault kv get "$__secret_path" | sed 's/\ \{1,\}/=/g'| sed 's:=n/a$:=:' | sed 1,11d > "$__local_path"
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

_vault_get "$secret_path" "$env"
