#!/usr/bin/env bash

function messageError() {
    exitCodeNumber=$?
    echo "================================================================================"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] on $(hostname)"
    echo "--------------------------------------------------------------------------------";
    echo "Exit code $exitCodeNumber"
    echo "$@"
    echo "--------------------------------------------------------------------------------";
    exit 1
}

messageError $@
