#!/usr/bin/env bash

VAULT_CONFIG_FILE=~/.vault-configuration

function vault_check_path() {
  source $VAULT_CONFIG_FILE
  tcctl vault token
  MSG="Get path from vault server"
  VAULT_SECRETS=$1
  VAULT_PATH=$(vault kv get $VAULT_SECRETS | sed 1,8d | head -1)
  echo $VAULT_PATH
}

vault_check_path $1
