#!/usr/bin/env bash

# shellcheck source="$CLI_DIR/tc/framework/functions"
# shellcheck source="$CLI_DIR/tc/app/aws/functions"
# shellcheck disable=SC2124,SC2034

source "$CLI_DIR/tc/framework/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --secret-path)
    SECRET_PATH="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

if [ -z "$SECRET_PATH" ]; then
  __MSG="Command: \033[36mtcctl vault path\033[39m missed --secret-path"
  _message_error "$__MSG"
else
  function vault_check_path() {
    tcctl helpers check_bin_file vault
    tcctl vault token
    SECRET_PATH="$1"
    __output=$( vault kv get "$SECRET_PATH" 2>&1 )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl vault path $@\033[39m\n"
    __MSG+="$__output"
    if [ $_error_code -eq "0" ]; then
      echo "true"
    else
      echo "false"
    fi
  }
  vault_check_path "$SECRET_PATH"
fi
