#!/usr/bin/env bash

# shellcheck disable=SC2196,SC2046,SC2124,SC2034,SC1091,SC2119

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --secret-path)
    SECRET_PATH="$2"
    shift 2
    ;;
    --env)
    ENV="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _vault_put() {
  _check_bin_file vault
  VAULT_TOKEN=$(_vault_get_token)
  export VAULT_TOKEN
  __secret_path=$1
  __env=$2
  __output=$(vault kv put "$__secret_path" $(egrep -v '^#' "$__env") 2>&1)
  _error_code=$?
  if [ "$_error_code" -eq "0" ]; then
    _vault_kv_put=$(echo "$__output" | xargs)
  else
    __MSG="Put to $__secret_path error"
    _message "$__MSG" "error" "$_error_code"
  fi
}

if [ -z "$SECRET_PATH" ]; then
  __MSG="Command: tcctl vault put missed --secret-path"
  _message_error "$__MSG"
elif [ -z "$ENV" ]; then
  __MSG="Command: tcctl vault put missed --env"
  _message "$__MSG" "error" "$_error_code"
else
  _vault_put "$SECRET_PATH" "$ENV"
fi
