#!/usr/bin/env bash

VAULT_CONFIG_FILE=~/.vault-configuration

function vault_put() {
  source $VAULT_CONFIG_FILE
  vaultctl token
  VAULT_SECRETS=$1
  ENV_FILE=$2
  MSG="Put to vault"
  vault kv put $VAULT_SECRETS $(egrep -v '^#' $ENV_FILE | xargs) \
    && tcctl message "Success. $MSG" \
    || tcctl messageError "Error. $MSG"
}

vault_put $1 $2
