#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"

addr=""

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

__output=$(curl -sL -w "%{http_code}\n" "$addr" -o /dev/null)
_error_code=$?
if [ "$_error_code" -eq "0" ]; then
  if [[ "$__output" == "200" ]]; then
    echo "true"
  fi
else
  echo "false"
fi
