#!/usr/bin/env bash

VAULT_CONFIG_FILE=~/.vault-configuration

# shellcheck source=$CLI_DIR/tc/framework/functions
# shellcheck source=$CLI_DIR/tc/app/aws/functions

source "$CLI_DIR/tc/framework/functions"

# shellcheck disable=SC2120,SC1090,SC2124,SC2034

function vault_get_token()  {
  tcctl helpers check_bin_file vault
  source $VAULT_CONFIG_FILE
  __output=$( vault login -method=userpass username="$VAULT_NAME" password="$VAULT_PASSWORD" )
  export _error_code=$?
  __MSG="Command: tcctl vault token $@"
  __MSG+="$__output"
  if [ $_error_code -eq "0" ]; then
    VAULT_TOKEN=$( echo "$__output" | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p )
  else
    _message "$__MSG" "error" "$_error_code"
  fi
}

vault_get_token
