#!/usr/bin/env bash

VAULT_CONFIG_FILE=~/.vault-configuration

function vault_get_token()  {
  source $VAULT_CONFIG_FILE
  MSG="Get token from vault server"
  VAULT_TOKEN=$(vault login -method=userpass username=${VAULT_NAME} password=${VAULT_PASSWORD} \
                | sed 1,6d | tr -s ' ' | cut -f 2 -d ' ' | sed -n 1p) \
    && tcctl message "Success. $MSG" \
    || tcctl messageError "Error. $MSG"
}

vault_get_token
