#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function restart_service() {
  SERVICE_NAME=$1
  OS=$( _get_os )
  if [[ $OS == Linux ]]; then
    SUDO_COMMAND="sudo "
    __output=$( $SUDO_COMMAND $SERVICE_NAME restart all )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 restart\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message_error "$__MSG"
    fi
  elif [[ $OS == Darwin ]]; then
    __output=$( $SERVICE_NAME restart all )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 restart\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message_error "$__MSG"
    fi
  fi
}

restart_service $1
