#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function start_service() {
  SERVICE_NAME=$1
  OS=$( get_os )
  if [[ $OS == Linux ]]; then
    SUDO_COMMAND="sudo "
    __output=$( $SUDO_COMMAND $SERVICE_NAME start all )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 start\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo $__output | column -t
    else
      message_error "$__MSG"
    fi
  elif [[ $OS == Darwin ]]; then
    SUDO_COMMAND=""
    __output=$( $SUDO_COMMAND $SERVICE_NAME start all )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 start\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo $__output | column -t
    else
      message_error "$__MSG"
    fi
  fi
}

start_service $1
