#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --service-name)
    SERVICE_NAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function start_service() {
    SERVICE_NAME=$1
    OS=$( _get_os )
    if [[ $OS == Linux ]]; then
      SUDO_COMMAND="sudo "
      __output=$( $SUDO_COMMAND service "$SERVICE_NAME" start )
      export _error_code=$?
      __MSG="Command: tcctl service $1 start"
      __MSG+="$__output"
      if [[ $_error_code -eq "0" ]]; then
        echo "$__output" | column -t
      else
        _message "$__MSG" "error" "$_error_code"
      fi
    elif [[ $OS == Darwin ]]; then
      __output=$( $SERVICE_NAME start all )
      export _error_code=$?
      __MSG="Command: tcctl service $1 start"
      __MSG+="$__output"
      if [[ $_error_code -eq "0" ]]; then
        echo "$__output" | column -t
      else
        _message "$__MSG" "error" "$_error_code"
      fi
    fi
}

if [ -z "$SERVICE_NAME" ]; then
  __MSG="Command: tcctl service start missed --service-name"
  _message "$__MSG" "error" "$_error_code"
else
  start_service "$SERVICE_NAME"
fi
