#!/usr/bin/env bash

# shellcheck source="$CLI_DIR/tc/framework/functions"
# shellcheck source="$CLI_DIR/tc/app/aws/functions"
# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --service-name)
    SERVICE_NAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

if [ -z "$SERVICE_NAME" ]; then
  __MSG="Command: \033[36mtcctl service status\033[39m missed --service-name"
  _message_error "$__MSG"
else
  function status_service() {
    SERVICE_NAME=$1
    OS=$( _get_os )
    if [[ $OS == Linux ]]; then
      systemctl is-active "$SERVICE_NAME" | column -t
    elif [[ $OS == Darwin ]]; then
      $SERVICE_NAME status | awk '{ print $2 }'
    fi
  }
  status_service "$SERVICE_NAME"
fi
