#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --service-name)
    SERVICE_NAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function stop_service() {
  __service_name=$1
  if [[ $( _get_os ) == Linux ]]; then
    __sudo_command="sudo "
    __output=$( $__sudo_command service "$__service_name" stop )
    _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  elif [[ $( _get_os ) == Darwin ]]; then
    __output=$( $__service_name stop all )
    _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  fi
}

if [ -z "$SERVICE_NAME" ]; then
  __MSG="Command: tcctl service stop missed --service-name"
  _message "$__MSG" "error" "$_error_code"
else
  stop_service "$SERVICE_NAME"
fi
