#!/usr/bin/env bash

# shellcheck source="$CLI_DIR/tc/framework/functions"
# shellcheck source="$CLI_DIR/tc/app/aws/functions"
# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

set +e

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --service-name)
    SERVICE_NAME="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function stop_service() {
  SERVICE_NAME=$1
  OS=$( _get_os )
  if [[ $OS == Linux ]]; then
    SUDO_COMMAND="sudo "
    __output=$( $SUDO_COMMAND service "$SERVICE_NAME" stop )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  elif [[ $OS == Darwin ]]; then
    __output=$( $SERVICE_NAME stop all )
    export _error_code=$?
    __MSG="Command: \033[36mtcctl service $1 stop\033[39m\n"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo "$__output" | column -t
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  fi
}

if [ -z "$SERVICE_NAME" ]; then
  __MSG="Command: tcctl service stop missed --service-name"
  _message "$__MSG" "error" "$_error_code"
else
  stop_service "$SERVICE_NAME"
fi
