#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function update_service() {
  SUDO_COMMAND=""
  SERVICE_NAME=$1
  OS=$2
  [[ $OS == Linux ]] && SUDO_COMMAND="sudo "
  __output=$( $SUDO_COMMAND $SERVICE_NAME update )
  export _error_code=$?
  __MSG="Command: \033[36mtcctl service $1 update\033[39m\n"
  __MSG+="$__output"
  if [[ $_error_code -eq "0" ]]; then
      echo $__output | column -t
  else
      message_error "$__MSG"
  fi
}

update_service $1 $2
