#!/usr/bin/env bash

# shellcheck source=$CLI_DIR/tc/framework/functions
. "${$CLI_DIR/tc/framework/functions}"

# shellcheck source=$CLI_DIR/tc/app/dns/functions
. "${$CLI_DIR/tc/app/dns/functions}"

root_cert_path=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -f "$root_cert_path" ]; then
  _cert_trust "$root_cert_path"
  __error_code=$?
  if [[ $__error_code -gt "0" ]]; then
    __MSG="File $root_cert_path doesn't exists"
    _message "$__MSG" "error" "$__error_code"
  fi
fi
