#!/usr/bin/env bash

# shellcheck source=$CLI_DIR/tc/framework/functions
. "${$CLI_DIR/tc/framework/functions}"

# shellcheck source=$CLI_DIR/tc/app/dns/functions
. "${$CLI_DIR/tc/app/dns/functions}"

dns_name=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

_cert_gen "$dns_name"
