#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/dns/functions"

cert_path=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if [ -f "$cert_path" ]; then
  _get_all_local_dns "$cert_path"
else
  __MSG="$cert_path doesn't exists"
  _message "$__MSG" "error"
fi
