#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

TIME="2"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --url)
    URL="$2"
    shift 2
    ;;
    --token)
    TOKEN="$2"
    shift 2
    ;;
    --time)
    TIME="$2"
    shift 2
    ;;
    --mode)
    MODE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function maintenance_mode_on() {
  if [[ -f $(command -v curl) ]]; then
    __maintenance_mode_mode="$1"
    __maintenance_mode_url="$2"
    __maintenance_mode_token="$3"
    __maintenance_mode_time="$4"
    if [[ $__maintenance_mode_mode = "on" ]]; then
      __METHOD="POST"
      __maintenance_mode_command="curl --location --request $__METHOD '$__maintenance_mode_url' \
          --header 'administration-api-token: $__maintenance_mode_token' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'minutes=$__maintenance_mode_time'"
      echo "$__maintenance_mode_command"
    else
      __METHOD="DELETE"
      __maintenance_mode_command="curl --location --request $__METHOD '$__maintenance_mode_url' \
          --header 'administration-api-token: $__maintenance_mode_token' \
          --header 'Content-Type: application/x-www-form-urlencoded'"
    fi

    __output=$( eval "$__maintenance_mode_command" )
    _error_code=$?
    __MSG="Command: tcctl maintenance on"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Maintenance mode activated on $__maintenance_mode_url"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  else
    echo "We can't find curl command"
    exit 1
  fi
}

maintenance_mode_on "$MODE" "$URL" "$TOKEN" "$TIME"
