#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

set -o pipefail

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --secret-path)
    SECRET_PATH="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function _vault_download() {
  _check_bin_file vault
  VAULT_TOKEN=$(tcctl vault token)
  export VAULT_TOKEN
  __secret_path=$1
  __file=$2
  rm -rf "$__file"
  if [ "$__secret_path" ] ; then
    __output=$( vault read "$__secret_path" -format=json | jq -r .data.key >> "$__file" )
    _error_code=$?
    __MSG="Command: tcctl vault download $__file from vault server "
    __MSG+="$__output"
    if [ "$_error_code" -eq "0" ]; then
      echo "Success! Data downloaded: $__secret_path -> $__file"
    fi
  fi
}

if [ -z "$FILE" ]; then
  __MSG="Command: tcctl vault file download missed --file"
  _message "$__MSG" "error" "$_error_code"
else
  _vault_download "$SECRET_PATH" "$FILE"
fi
