#!/usr/bin/env bash

# shellcheck disable=SC1091

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/vault/functions"
source "$CLI_DIR/tc/app/helpers/functions"

set -o pipefail

auth_type=
secret_path=
file=
token=
name=
pass=
addr=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

_check_bin_file vault
_vault_authorization "$auth_type" "$name" "$pass" "$token" "$addr"
#rm -rf "$file"
if [ "$secret_path" ] ; then
  vault read "$secret_path" -format=json | jq -r .data.key > "$file"
  _error_code=$?
  if [ "$_error_code" -eq "0" ]; then
    echo "Downloading $file from $secret_path is successfully"
  else
    __MSG="Error while downloading $file from $secret_path"
    _message "$__MSG" "error" "$_error_code"
  fi
fi
