#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

set +e

CHANNEL="devops-notifications"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --site-version)
    SITE_VERSION="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function slack_file_upload() {
    __output=$( slack file upload "$3" "$1" --comment "Changes in version $2 on :host: $(hostname)" )
    _error_code=$?
    __MSG="Command: tcctl slack file_upload"
    __MSG+="$__output"
    if [[ $_error_code -eq "0" ]]; then
      echo "$__output"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
}

if [ -z "$CHANNEL" ]; then
  __MSG="Command: slack file upload"
  _message "$__MSG" "error" "$_error_code"
else
  slack_file_upload "$CHANNEL" "$SITE_VERSION" "$FILE"
fi
