#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"
source "$CLI_DIR/tc/app/slack/functions"

CHANNEL="#devops-notifications"
MESSAGE="Hostname: $(hostname)"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    --message)
    MESSAGE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

slack_file_upload "$CHANNEL" "$MESSAGE" "$FILE"
