#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

CHANNEL="#devops-notifications"
MESSAGE="Hostname: $(hostname)"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    --message)
    MESSAGE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function slack_file_upload() {
  if [[ -f $(command -v slack) ]] && [[ -f "$FILE" ]]; then
    __output=$( slack file upload "$3" "$1" --comment "$2" )
    _error_code=$?
    __MSG="Command: tcctl slack file_upload"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Message was send into Slack $CHANNEL"
    else
      _message "$__MSG" "warning"
    fi
  else
    echo "We can't find slack command or commnts_summary file"
    exit 1
  fi
}

slack_file_upload "$CHANNEL" "$MESSAGE" "$FILE"
