#!/usr/bin/env bash

# shellcheck disable=SC1090

__slack_channel="#devops-notifications"

function slack_send_message() {
  if [[ -f $(command -v slack) ]]; then
    __slack_message="$1"
    __slack_color="$3"
    __slack_channel="$2"
    if [[ -n $__slack_color ]]; then
      __slack_color="-cl \"$__slack_color\""
    fi
    __slack_command="$(command -v slack) chat send $__slack_color "\"$__slack_message\"" "\"$__slack_channel\"""
    __output=$( eval "$__slack_command" )
    _error_code=$?
    __MSG="Command: tcctl slack update_finish"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Message was send into Slack $CHANNEL"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
  else
    echo "We can't find slack command"
    exit 1
  fi
}

function slack_file_upload() {
  if [[ -f $(command -v slack) ]] && [[ -f "$FILE" ]]; then
    __slack_channel="$1"
    __slack_message="$2"
    __slack_file="$3"
    __output=$( slack file upload "$__slack_file" "$__slack_channel" --comment "$__slack_message" )
    _error_code=$?
    __MSG="Command: tcctl slack file_upload"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Message was send into Slack $CHANNEL"
    else
      _message "$__MSG" "warning"
    fi
  else
    echo "We can't find slack command or commnts_summary file"
    exit 1
  fi
}

