#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

CHANNEL="#devops-notifications"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --url)
    URL="$2"
    shift 2
    ;;
    --pull-request-url)
    PULLREQUEST_URL="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function slack_pr_information() {
    SLACK_COLOR="#6dc56d"
    SLACK_MESSAGE="QA Team need to check before the deploy. Pre-production link $2\n"
    SLACK_MESSAGE+="Approve or Decline this request on the Bitbucket.\nSee changes here: $3"
    __output=$( slack chat send -cl "$SLACK_COLOR" "$SLACK_MESSAGE" "$1" )
    _error_code=$?
    __MSG="Command: tcctl slack send_pull_request"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Message was send into Slack $CHANNEL"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
}

slack_pr_information "$CHANNEL" "$URL" "$PULLREQUEST_URL"
