#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

CHANNEL="#devops-notifications"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --channel)
    CHANNEL="$2"
    shift 2
    ;;
    --file)
    FILE="$2"
    shift 2
    ;;
    *)
    ;;
esac
done

function slack_solved_issue_list() {
    SLACK_MESSAGE="The list of solved problems when deploying (:host: $(hostname) ):\n"
    SLACK_MESSAGE+="$(cat $2 | egrep -oh 'TC-[0-9]+' | sort -u | awk '{print "https://tenantcloud.atlassian.net/browse/" $1}')"
    __output=$( slack chat send "$SLACK_MESSAGE" "$1" )
    _error_code=$?
    __MSG="Command: tcctl slack solved_list"
    __MSG+="$__output"
    if [[ "$_error_code" -eq "0" ]]; then
      _message "Message was send into Slack $CHANNEL"
    else
      _message "$__MSG" "error" "$_error_code"
    fi
}

slack_solved_issue_list "$CHANNEL" "$FILE"
