#!/usr/bin/env bash

source "$CLI_DIR/tc/framework/functions"

function get_value_from_env() {
  if [[ -f "$2" ]]; then
      VARIABLE=$1
      FILENAME=$2
      __output=$( sed -n -e "s/^\s*$VARIABLE\s*=//p" $FILENAME )
      export _error_code=$?
      __MSG="Command: \033[36mtcctl helpers get value from env $1\033[39m\n"
      __MSG+="$__output"
  if [ $_error_code -eq "0" ]; then
    if [[ -z "$__output" ]]; then
      exit 1
    else
      echo $__output
    fi
  else
    message_error "$__MSG"
  fi
  fi
}

get_value_from_env $1 $2
