#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

container_name=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

if ( docker stats --no-stream > /dev/null 2>&1 ); then
  docker-compose ps -q "$container_name" > /dev/null 2>&1
  __error_code=$?
  if [[ $__error_code -eq "0" ]]; then
    _message "Stop $container_name container"
    docker-compose rm -s -v -f "$container_name"
    __error_code=$?
    _message "Start $container_name container"
    docker-compose up -d "$container_name"
    __error_code+=$?
    if [[ $__error_code -gt "0" ]]; then
      __MSG="Error when restarting $container_name container"
      _message "$__MSG" "error" "$__error_code"
    fi
  else
    __MSG="Container doesn't exist"
    _message "$__MSG" "error" "$__error_code"
  fi
else
  __MSG="Docker daemon is not launched for the local machine"
  _message "$__MSG" "error" "$__error_code"
  exit 1
fi
