#!/usr/bin/env bash

# shellcheck disable=SC1090

source "$CLI_DIR/tc/framework/functions"

container_name=

while echo "$1" | grep -q ^--; do
  __key=${1//--/}
  __key=${__key//-/_}
  if [[ -n "$2" ]]; then
    eval "${__key}"='$2'
    shift 2
  else
    set "${__key}"
    shift
  fi
done

__cid=$(docker ps -q -f status=running -f name=^/tc-home-"$container_name")
if [ "$container_name" == "app" ]; then
  container_name="home"
fi
if [ ! "${__cid}" ]; then
  _message "Container doesn't exist"
else
  _message "Stop $container_name container"
  docker-compose rm -s -v -f "$container_name"
  __error_code=$?
  _message "Start $container_name container"
  docker-compose up -d "$container_name"
  __error_code+=$?
fi
if [[ $__error_code -gt "0" ]]; then
  __MSG="Error when restarting $1 container"
  _message "$__MSG" "error" "$__error_code"
fi
